#!/usr/bin/env node
/**
 * Converts every Zoom reference icon in docs/reference/icons/*.svg into a typed
 * React component under frontend/src/shared/icons/generated/ (+ index.ts) and
 * copies the PNG assets to frontend/public/zoom/.
 *
 * Usage: `node scripts/gen-icons.mjs` (or `npm run gen:icons` in frontend/).
 * The output is committed; re-run after adding icons. Never edit the output.
 */
import { copyFileSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const ICONS_DIR = path.join(ROOT, "docs/reference/icons");
const OUT_DIR = path.join(ROOT, "frontend/src/shared/icons/generated");
const PUBLIC_DIR = path.join(ROOT, "frontend/public/zoom");

/** Root <svg> attributes that are replaced by component props or dropped. */
const DROPPED_ROOT_ATTRS = new Set(["width", "height", "xmlns", "xmlns:xlink", "style", "id", "x", "y", "version", "class"]);

const toPascalCase = (slug) =>
  slug
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join("");

const camelCase = (name) => name.replace(/[-:]([a-z])/g, (_, ch) => ch.toUpperCase());

function jsxAttrName(name) {
  if (name === "class") return "className";
  if (name === "xlink:href") return "href";
  if (name === "xml:space") return "xmlSpace";
  if (name.startsWith("data-") || name.startsWith("aria-")) return name;
  return camelCase(name);
}

function styleToObject(css) {
  const entries = css
    .split(";")
    .map((decl) => decl.trim())
    .filter(Boolean)
    .map((decl) => {
      const [prop, ...rest] = decl.split(":");
      return `${camelCase(prop.trim())}: ${JSON.stringify(rest.join(":").trim())}`;
    });
  return `{{ ${entries.join(", ")} }}`;
}

function parseAttrs(source) {
  const attrs = [];
  const re = /([a-zA-Z_:][-a-zA-Z0-9_:.]*)\s*=\s*("([^"]*)"|'([^']*)')/g;
  for (const match of source.matchAll(re)) attrs.push([match[1], match[3] ?? match[4]]);
  return attrs;
}

/** Makes ids unique per icon so several icons can share a page. */
function prefixIdRefs(name, value, prefix) {
  if (name === "id") return `${prefix}-${value}`;
  if ((name === "href" || name === "xlink:href") && value.startsWith("#")) return `#${prefix}-${value.slice(1)}`;
  return value.replace(/url\(#([^)]+)\)/g, `url(#${prefix}-$1)`);
}

function convertAttrs(source, prefix) {
  return parseAttrs(source)
    .filter(([name]) => name !== "xmlns:xlink")
    .map(([name, value]) => {
      if (name === "style") return `style=${styleToObject(value)}`;
      return `${jsxAttrName(name)}=${JSON.stringify(prefixIdRefs(name, value, prefix))}`;
    })
    .join(" ");
}

function convertInner(markup, prefix) {
  return markup
    .replace(/<!--[\s\S]*?-->/g, "")
    .replace(/>\s+</g, "><")
    .trim()
    .replace(/<([a-zA-Z][a-zA-Z0-9]*)((?:\s+[^>]*?)?)(\/?)>/g, (_, tag, attrs, selfClosing) => {
      const converted = convertAttrs(attrs, prefix);
      return `<${tag}${converted ? ` ${converted}` : ""}${selfClosing ? " /" : ""}>`;
    });
}

function parseSvg(source) {
  const cleaned = source.replace(/<\?xml[\s\S]*?\?>/g, "").replace(/<!--[\s\S]*?-->/g, "").trim();
  const open = cleaned.match(/<svg\b([^>]*)>/);
  if (!open) throw new Error("No <svg> root");
  const inner = cleaned.slice(open.index + open[0].length, cleaned.lastIndexOf("</svg>"));
  return { rootAttrs: parseAttrs(open[1]), inner };
}

function sizeLiteral(value) {
  if (value === undefined) return '"1em"';
  return /^\d+(\.\d+)?$/.test(value) ? value : JSON.stringify(value);
}

function renderComponent(file, name, slug) {
  const { rootAttrs, inner } = parseSvg(readFileSync(path.join(ICONS_DIR, file), "utf8"));
  const attr = Object.fromEntries(rootAttrs);
  const width = sizeLiteral(attr.width);
  const height = sizeLiteral(attr.height);
  const isSquare = width === height;
  const ratio = isSquare ? 1 : Number(attr.width) / Number(attr.height);
  const widthExpr = isSquare
    ? `size ?? ${width}`
    : `size === undefined ? ${width} : typeof size === "number" ? size * ${ratio} : undefined`;
  const rootProps = rootAttrs
    .filter(([key]) => !DROPPED_ROOT_ATTRS.has(key))
    .map(([key, value]) => `      ${jsxAttrName(key)}=${JSON.stringify(value)}`)
    .join("\n");
  const body = convertInner(inner, slug);
  return `// Generated by scripts/gen-icons.mjs from docs/reference/icons/${file} — do not edit.
import type { IconProps } from "../types";

export function ${name}({ size, title, ...props }: IconProps) {
  return (
    <svg
      width={${widthExpr}}
      height={size ?? ${height}}
${rootProps}
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden={title ? undefined : true}
      role={title ? "img" : undefined}
      focusable="false"
      {...props}
    >
      {title ? <title>{title}</title> : null}
      ${body}
    </svg>
  );
}
`;
}

function main() {
  const files = readdirSync(ICONS_DIR).sort();
  rmSync(OUT_DIR, { recursive: true, force: true });
  mkdirSync(OUT_DIR, { recursive: true });
  mkdirSync(PUBLIC_DIR, { recursive: true });

  const exports = [];
  for (const file of files) {
    if (file.endsWith(".png")) {
      copyFileSync(path.join(ICONS_DIR, file), path.join(PUBLIC_DIR, file));
      continue;
    }
    if (!file.endsWith(".svg")) continue;
    const slug = file.replace(/\.svg$/, "");
    const name = `${toPascalCase(slug)}Icon`;
    writeFileSync(path.join(OUT_DIR, `${name}.tsx`), renderComponent(file, name, slug));
    exports.push(`export { ${name} } from "./${name}";`);
  }
  const header = "// Generated by scripts/gen-icons.mjs — do not edit. One component per docs/reference/icons/*.svg.\n";
  writeFileSync(path.join(OUT_DIR, "index.ts"), `${header}${exports.join("\n")}\n`);
  console.log(`gen-icons: ${exports.length} components, PNGs copied to public/zoom/`);
}

main();
