/**
 * Zoom's 149 Schedule-page time zones in menu order (03-schedule.md Appendix B),
 * the same list as backend/app/services/timezone_data.py. The `(GMT±H:MM)`
 * prefix depends on the current DST offset and is computed at runtime.
 */
export const TIME_ZONES: readonly (readonly [iana: string, label: string])[] = [
  ["Pacific/Midway", "Midway Island, Samoa"],
  ["Pacific/Pago_Pago", "Pago Pago"],
  ["Pacific/Honolulu", "Hawaii"],
  ["America/Adak", "Aleutian Islands"],
  ["America/Anchorage", "Alaska"],
  ["America/Juneau", "Juneau"],
  ["America/Vancouver", "Vancouver"],
  ["America/Los_Angeles", "Pacific Time (US and Canada)"],
  ["America/Tijuana", "Tijuana"],
  ["America/Phoenix", "Arizona"],
  ["America/Mazatlan", "Mazatlan"],
  ["America/Whitehorse", "Yukon"],
  ["America/Edmonton", "Edmonton"],
  ["America/Denver", "Mountain Time (US and Canada)"],
  ["America/Regina", "Saskatchewan"],
  ["America/Mexico_City", "Mexico City"],
  ["America/Guatemala", "Guatemala"],
  ["America/El_Salvador", "El Salvador"],
  ["America/Managua", "Managua"],
  ["America/Costa_Rica", "Costa Rica"],
  ["America/Tegucigalpa", "Tegucigalpa"],
  ["America/Chihuahua", "Chihuahua"],
  ["America/Monterrey", "Monterrey"],
  ["America/Winnipeg", "Winnipeg"],
  ["America/Chicago", "Central Time (US and Canada)"],
  ["America/Panama", "Panama"],
  ["America/Bogota", "Bogota"],
  ["America/Lima", "Lima"],
  ["America/Eirunepe", "Acre"],
  ["America/Montreal", "Montreal"],
  ["America/New_York", "Eastern Time (US and Canada)"],
  ["America/Indianapolis", "Indiana (East)"],
  ["America/Puerto_Rico", "Puerto Rico"],
  ["America/Caracas", "Caracas"],
  ["America/La_Paz", "La Paz"],
  ["America/Guyana", "Guyana"],
  ["America/Halifax", "Halifax"],
  ["America/Santiago", "Santiago"],
  ["America/Montevideo", "Montevideo"],
  ["America/Araguaina", "Recife"],
  ["America/Argentina/Buenos_Aires", "Buenos Aires, Georgetown"],
  ["America/Sao_Paulo", "Sao Paulo"],
  ["Canada/Atlantic", "Atlantic Time (Canada)"],
  ["America/St_Johns", "Newfoundland and Labrador"],
  ["America/Noronha", "Fernando de Noronha"],
  ["America/Godthab", "Greenland"],
  ["Atlantic/Cape_Verde", "Cape Verde Islands"],
  ["Atlantic/Azores", "Azores"],
  ["UTC", "Universal Time UTC"],
  ["Etc/Greenwich", "Greenwich Mean Time"],
  ["Atlantic/Reykjavik", "Reykjavik"],
  ["Africa/Casablanca", "Casablanca"],
  ["Africa/Nouakchott", "Nouakchott"],
  ["Europe/Dublin", "Dublin"],
  ["Europe/London", "London"],
  ["Europe/Lisbon", "Lisbon"],
  ["Africa/Bangui", "West Central Africa"],
  ["Africa/Algiers", "Algiers"],
  ["Africa/Tunis", "Tunis"],
  ["Europe/Belgrade", "Belgrade, Bratislava, Ljubljana"],
  ["CET", "Sarajevo, Skopje, Zagreb"],
  ["Europe/Oslo", "Oslo"],
  ["Europe/Copenhagen", "Copenhagen"],
  ["Europe/Brussels", "Brussels"],
  ["Europe/Berlin", "Amsterdam, Berlin, Rome, Stockholm, Vienna"],
  ["Europe/Amsterdam", "Amsterdam"],
  ["Europe/Rome", "Rome"],
  ["Europe/Stockholm", "Stockholm"],
  ["Europe/Vienna", "Vienna"],
  ["Europe/Luxembourg", "Luxembourg"],
  ["Europe/Paris", "Paris"],
  ["Europe/Zurich", "Zurich"],
  ["Europe/Madrid", "Madrid"],
  ["Africa/Harare", "Harare, Pretoria"],
  ["Europe/Warsaw", "Warsaw"],
  ["Europe/Prague", "Prague Bratislava"],
  ["Europe/Budapest", "Budapest"],
  ["Africa/Tripoli", "Tripoli"],
  ["Africa/Johannesburg", "Johannesburg"],
  ["Africa/Khartoum", "Khartoum"],
  ["Europe/Helsinki", "Helsinki"],
  ["Africa/Nairobi", "Nairobi"],
  ["Europe/Sofia", "Sofia"],
  ["Europe/Istanbul", "Istanbul"],
  ["Europe/Athens", "Athens"],
  ["Europe/Bucharest", "Bucharest"],
  ["Asia/Nicosia", "Nicosia"],
  ["Asia/Beirut", "Beirut"],
  ["Asia/Damascus", "Damascus"],
  ["Asia/Jerusalem", "Jerusalem"],
  ["Asia/Amman", "Amman"],
  ["Africa/Cairo", "Cairo"],
  ["Europe/Moscow", "Moscow"],
  ["Asia/Baghdad", "Baghdad"],
  ["Asia/Kuwait", "Kuwait"],
  ["Asia/Riyadh", "Riyadh"],
  ["Asia/Bahrain", "Bahrain"],
  ["Asia/Qatar", "Qatar"],
  ["Asia/Aden", "Aden"],
  ["Africa/Djibouti", "Djibouti"],
  ["Africa/Mogadishu", "Mogadishu"],
  ["Europe/Kiev", "Kyiv"],
  ["Europe/Minsk", "Minsk"],
  ["Europe/Chisinau", "Chisinau"],
  ["Asia/Tehran", "Tehran"],
  ["Asia/Dubai", "Dubai"],
  ["Asia/Muscat", "Muscat"],
  ["Asia/Baku", "Baku, Tbilisi, Yerevan"],
  ["Asia/Kabul", "Kabul"],
  ["Asia/Yekaterinburg", "Yekaterinburg"],
  ["Asia/Tashkent", "Islamabad, Karachi, Tashkent"],
  ["Asia/Almaty", "Astana, Almaty"],
  ["Asia/Calcutta", "India"],
  ["Asia/Kolkata", "Mumbai, Kolkata, New Delhi"],
  ["Asia/Colombo", "Colombo"],
  ["Asia/Kathmandu", "Kathmandu"],
  ["Asia/Dacca", "Dacca"],
  ["Asia/Dhaka", "Dhaka"],
  ["Asia/Rangoon", "Rangoon"],
  ["Asia/Novosibirsk", "Novosibirsk"],
  ["Asia/Krasnoyarsk", "Krasnoyarsk"],
  ["Asia/Bangkok", "Bangkok"],
  ["Asia/Saigon", "Vietnam"],
  ["Asia/Jakarta", "Jakarta"],
  ["Asia/Irkutsk", "Irkutsk, Ulaanbaatar"],
  ["Asia/Shanghai", "Beijing, Shanghai"],
  ["Asia/Hong_Kong", "Hong Kong SAR"],
  ["Asia/Taipei", "Taipei"],
  ["Asia/Kuala_Lumpur", "Kuala Lumpur"],
  ["Asia/Singapore", "Singapore"],
  ["Australia/Perth", "Perth"],
  ["Asia/Yakutsk", "Yakutsk"],
  ["Asia/Seoul", "Seoul"],
  ["Asia/Tokyo", "Osaka, Sapporo, Tokyo"],
  ["Australia/Darwin", "Darwin"],
  ["Asia/Vladivostok", "Vladivostok"],
  ["Pacific/Port_Moresby", "Guam, Port Moresby"],
  ["Australia/Brisbane", "Brisbane"],
  ["Australia/Adelaide", "Adelaide"],
  ["Australia/Sydney", "Canberra, Melbourne, Sydney"],
  ["Australia/Hobart", "Hobart"],
  ["Australia/Lord_Howe", "Lord Howe IsIand"],
  ["Asia/Magadan", "Magadan"],
  ["Pacific/Guadalcanal", "Solomon Islands"],
  ["Pacific/Noumea", "New Caledonia"],
  ["Asia/Kamchatka", "Kamchatka"],
  ["Pacific/Fiji", "Fiji Islands, Marshall Islands"],
  ["Pacific/Auckland", "Auckland, Wellington"],
  ["Pacific/Apia", "Independent State of Samoa"],
];
